// Snapshot-style checks on the SessionShareAdapter context shape, plus the
// long-list truncation in the default text template. No Realm I/O — service
// dependencies stubbed.

import {assert} from "chai";
import _ from "lodash";

jest.mock("../../../src/framework/bean/Service", () => () => (target) => target);
// PDFGenerationService transitively imports these native modules; mock them so
// the test file can load without a TurboModule registry.
jest.mock("react-native-share", () => ({open: jest.fn(() => Promise.resolve())}));
jest.mock("react-native-html-to-pdf", () => ({convert: jest.fn(() => Promise.resolve({filePath: "/tmp/x.pdf"}))}));

import {AttendanceRecord} from "avni-models";
import SessionShareAdapter from "../../../src/service/attendance/SessionShareAdapter";

function makeAdapter({recordService, individualService, conceptService, i18nMap = {}}) {
    const pdfService = {getFooterText: () => "Generated by Avni · marker · 22-05-2026 09:00"};
    const messageService = {
        getI18n: () => ({
            t: (key, params) => {
                if (!params) return i18nMap[key] || key;
                let s = i18nMap[key] || key;
                Object.keys(params).forEach(k => {
                    s = s.replace(`{{${k}}}`, String(params[k]));
                });
                return s;
            },
        }),
    };
    const beanStore = {
        beansMap: new Map([
            ["attendanceRecordService", recordService],
            ["individualService", individualService],
            ["conceptService", conceptService],
            ["pdfGenerationService", pdfService],
            ["messageService", messageService],
        ]),
    };
    // BaseService.getService(klass) reads beansMap by class — bypass by stubbing
    // it to return our injected stubs keyed off the require'd class name.
    const lookup = new Map([
        [require("../../../src/service/AttendanceRecordService").default, recordService],
        [require("../../../src/service/IndividualService").default, individualService],
        [require("../../../src/service/ConceptService").default, conceptService],
        [require("../../../src/service/PDFGenerationService").default, pdfService],
        [require("../../../src/service/MessageService").default, messageService],
    ]);
    const adapter = new SessionShareAdapter({}, beanStore);
    adapter.getService = (klass) => lookup.get(klass);
    adapter.init();
    return adapter;
}

const PRESENT = AttendanceRecord.status.PRESENT;
const ABSENT = AttendanceRecord.status.ABSENT;

describe("SessionShareAdapter.buildContext — summary shape", () => {
    let adapter;
    let session;
    let attendanceType;
    let groupSubject;

    beforeEach(() => {
        session = {uuid: "sess-1", scheduledDate: "2026-05-21", status: "Held", notes: "Started late."};
        attendanceType = {uuid: "at-1", name: "Morning Prayer"};
        groupSubject = {uuid: "g-1", nameString: "Class 7A"};

        const records = [
            {uuid: "r1", subjectUUID: "s1", status: PRESENT, reasonConceptUUID: null, followUpEncounterUUID: null, voided: false},
            {uuid: "r2", subjectUUID: "s2", status: ABSENT, reasonConceptUUID: "rc-sick", followUpEncounterUUID: null, voided: false},
            {uuid: "r3", subjectUUID: "s3", status: ABSENT, reasonConceptUUID: null, followUpEncounterUUID: "fu-1", voided: false},
            {uuid: "r4", subjectUUID: "s4", status: PRESENT, reasonConceptUUID: null, followUpEncounterUUID: null, voided: true},
        ];
        const individuals = {
            "s1": {uuid: "s1", nameString: "Aarav"},
            "s2": {uuid: "s2", nameString: "Esha"},
            "s3": {uuid: "s3", nameString: "Chirag"},
            "s4": {uuid: "s4", nameString: "Voided Student"},
        };
        const concepts = {"rc-sick": {uuid: "rc-sick", name: "Sick"}};

        adapter = makeAdapter({
            recordService: {findBySession: jest.fn(() => records)},
            individualService: {findByUUID: jest.fn(uuid => individuals[uuid] || null)},
            conceptService: {getConceptByUUID: jest.fn(uuid => concepts[uuid] || null)},
        });
    });

    it("produces the {entity, attendanceType, attendanceRecords, summary} top-level shape", () => {
        const ctx = adapter.buildContext(session, attendanceType, groupSubject);

        assert.equal(ctx.entity, session);
        assert.equal(ctx.attendanceType, attendanceType);
        assert.isArray(ctx.attendanceRecords);
        assert.isObject(ctx.summary);
    });

    it("skips voided AttendanceRecords", () => {
        const ctx = adapter.buildContext(session, attendanceType, groupSubject);
        const names = ctx.attendanceRecords.map(r => r.studentName);
        assert.notInclude(names, "Voided Student");
        assert.equal(ctx.attendanceRecords.length, 3);
    });

    it("resolves reasonName via ConceptService and omits it when no reason is set", () => {
        const ctx = adapter.buildContext(session, attendanceType, groupSubject);
        const esha = ctx.attendanceRecords.find(r => r.studentName === "Esha");
        const chirag = ctx.attendanceRecords.find(r => r.studentName === "Chirag");
        assert.equal(esha.reasonName, "Sick");
        assert.isUndefined(chirag.reasonName, "no reason -> reasonName key absent");
    });

    it("carries followUpEncounterUUID through for rules that want richer data", () => {
        const ctx = adapter.buildContext(session, attendanceType, groupSubject);
        const chirag = ctx.attendanceRecords.find(r => r.studentName === "Chirag");
        assert.equal(chirag.followUpEncounterUUID, "fu-1");
    });

    it("populates summary counts + names + group / type / date metadata", () => {
        const ctx = adapter.buildContext(session, attendanceType, groupSubject);
        const s = ctx.summary;
        assert.equal(s.groupName, "Class 7A");
        assert.equal(s.attendanceTypeName, "Morning Prayer");
        assert.equal(s.scheduledDate, "2026-05-21");
        assert.equal(s.presentCount, 1);
        assert.equal(s.absentCount, 2);
        assert.deepEqual(s.presentNames, ["Aarav"]);
        assert.deepEqual(s.absentNames, ["Esha", "Chirag"]);
        assert.equal(s.sessionStatus, "Held");
        assert.equal(s.sessionNotes, "Started late.");
    });
});

describe("SessionShareAdapter.defaultTextFromSummary — truncation", () => {
    let adapter;

    beforeEach(() => {
        adapter = makeAdapter({
            recordService: {findBySession: jest.fn(() => [])},
            individualService: {findByUUID: jest.fn(() => null)},
            conceptService: {getConceptByUUID: jest.fn(() => null)},
            i18nMap: {
                attendanceShareTextHeader: "Attendance for {{group}} — {{type}} on {{date}}:",
                attendanceShareTextCounts: "{{present}} present, {{absent}} absent.",
                attendanceShareTextAbsent: "Absent: {{names}}.",
                attendanceShareTextAbsentWithMore: "Absent: {{names}} ...and {{count}} more.",
            },
        });
    });

    it("renders absent names inline when count is within cap", () => {
        const summary = {
            groupName: "Class 7A", attendanceTypeName: "Morning Prayer", scheduledDate: "2026-05-21",
            presentCount: 8, absentCount: 2, presentNames: [], absentNames: ["Esha", "Chirag"],
            sessionStatus: "Held", sessionNotes: "",
        };

        const text = adapter.defaultTextFromSummary(summary);

        assert.include(text, "Absent: Esha, Chirag.");
        assert.notInclude(text, "more");
    });

    it("truncates with '...and N more' past the cap (WhatsApp preview safety)", () => {
        const names = _.range(1, 41).map(i => `Student${i}`);  // 40 names; cap is 30
        const summary = {
            groupName: "Class 7A", attendanceTypeName: "Morning Prayer", scheduledDate: "2026-05-21",
            presentCount: 5, absentCount: 40, presentNames: [], absentNames: names,
            sessionStatus: "Held", sessionNotes: "",
        };

        const text = adapter.defaultTextFromSummary(summary);

        // First 30 names are visible; "...and 10 more" caps the tail.
        assert.include(text, "Student1,");
        assert.include(text, "Student30");
        assert.notInclude(text, "Student31");
        assert.include(text, "...and 10 more");
    });

    it("emits no absent-line when nobody was absent (graceful zero case)", () => {
        const summary = {
            groupName: "Class 7A", attendanceTypeName: "Morning Prayer", scheduledDate: "2026-05-21",
            presentCount: 10, absentCount: 0, presentNames: [], absentNames: [],
            sessionStatus: "Held", sessionNotes: "",
        };

        const text = adapter.defaultTextFromSummary(summary);

        assert.notInclude(text, "Absent:");
        assert.include(text, "0 absent");
    });

    it("renders the DidntHappen branch when the session didn't happen", () => {
        const summary = {
            groupName: "Class 7A", attendanceTypeName: "Morning Prayer", scheduledDate: "2026-05-21",
            presentCount: 0, absentCount: 0, presentNames: [], absentNames: [],
            sessionStatus: "DidntHappen", sessionNotes: "",
        };
        adapter.I18n.t = (key, params) => key === "attendanceShareDidntHappenText" ? "Session did not happen." : (
            key === "attendanceShareTextHeader" ? `Attendance for ${params.group} — ${params.type} on ${params.date}:` : key
        );

        const text = adapter.defaultTextFromSummary(summary);

        assert.include(text, "Session did not happen.");
    });
});
