export default {
    GET_QUESTIONNAIRES: "GET_QUESTIONNAIRES",
    GET_CONFIG: "GET_CONFIG",
    RAISE_ERROR: "RAISE_ERROR",
    START_NEW_INDIVIDUAL_SEARCH: "START_NEW_INDIVIDUAL_SEARCH",
    ENTER_NAME_CRITERIA: "ENTER_NAME_CRITERIA",
    ENTER_AGE_CRITERIA: "ENTER_AGE_CRITERIA",
    ADD_ADDRESS_LEVEL_CRITERIA: "ENTER_ADDRESS_LEVEL_CRITERIA",
    REMOVE_ADDRESS_LEVEL_CRITERIA: "REMOVE_ADDRESS_LEVEL_CRITERIA",
    SEARCH_INDIVIDUALS: "SEARCH_INDIVIDUALS"
}