export default {
    GET_QUESTIONNAIRES: "GET_QUESTIONNAIRES",
    GET_CONFIG: "GET_CONFIG",
    RAISE_ERROR: "RAISE_ERROR",
    GET_ADDRESS_LEVELS: "GET_ADDRESS_LEVELS",
    ENTER_NAME_CRITERIA: "ENTER_NAME_CRITERIA",
    ENTER_AGE_CRITERIA: "ENTER_AGE_CRITERIA",
    TOGGLE_INDIVIDUAL_SEARCH_ADDRESS_LEVEL: "TOGGLE_INDIVIDUAL_SEARCH_ADDRESS_LEVEL",
    SEARCH_INDIVIDUALS: "SEARCH_INDIVIDUALS",
    TOGGLE_INDIVIDUAL_REGISTER_ADDRESS_LEVEL: "TOGGLE_INDIVIDUAL_REGISTER_ADDRESS_LEVEL",
    "REGISTER_ENTER_INDIVIDUAL_DATA_ELEMENTS": "REGISTER_ENTER_INDIVIDUAL_DATA_ELEMENTS"
}