/**
 * SqliteFactory - Creates and initializes an op-sqlite database.
 *
 * Responsibilities:
 * 1. Open op-sqlite database instance (with optional encryption)
 * 2. Run drizzle-kit generated migrations
 * 3. Seed initial Settings row
 * 4. Provide UserInfo seeding for post-login initialization
 */

import {EntityMappingConfig} from "openchs-models";
import EncryptionService from "../../service/EncryptionService";
import _ from "lodash";
import MigrationRunner from "./MigrationRunner";
import SchemaGenerator from "./SchemaGenerator";
import SqliteProxy from "./SqliteProxy";
import Config from "../Config";
import InitialSettings from "../../../config/initialSettings.json";
import General from "../../utility/General";

// Import bundled drizzle-kit migrations (generated by scripts/bundle-migrations.js)
import {journal, sqlFiles} from "./migrations/drizzleMigrations";

const DB_NAME = "avni_sqlite.db";

class SqliteFactory {
    static async createSqliteDb() {
        const {open} = require("@op-engineering/op-sqlite");

        const dbOptions = {name: DB_NAME};

        const encryptionKey = await EncryptionService.getEncryptionKey();
        if (!_.isNil(encryptionKey)) {
            if (encryptionKey instanceof Uint8Array || encryptionKey instanceof ArrayBuffer) {
                const bytes = encryptionKey instanceof ArrayBuffer
                    ? new Uint8Array(encryptionKey)
                    : encryptionKey;
                dbOptions.encryptionKey = Array.from(bytes)
                    .map(b => b.toString(16).padStart(2, "0"))
                    .join("");
            } else if (typeof encryptionKey === "string") {
                dbOptions.encryptionKey = encryptionKey;
            }
            General.logInfo("SqliteFactory", `Opening database with encryption (key length: ${dbOptions.encryptionKey.length} chars)`);
        } else {
            General.logInfo("SqliteFactory", "Opening database without encryption (no key found)");
        }

        const db = open(dbOptions);

        // Set PRAGMAs before migrations
        db.executeSync("PRAGMA journal_mode = WAL");
        db.executeSync("PRAGMA foreign_keys = OFF");

        const runner = new MigrationRunner(db);
        const result = runner.runMigrations(journal, sqlFiles);
        General.logInfo("SqliteFactory", `Database initialized (idx ${result.from} → ${result.to})`);

        db.executeSync("PRAGMA foreign_keys = ON");

        SqliteFactory._seedSettings(db);

        return db;
    }

    // Column names must match Settings schema in openchs-models.
    // If Settings schema changes, update this INSERT accordingly.
    static _seedSettings(db) {
        const existing = db.executeSync('SELECT "uuid" FROM settings LIMIT 1');
        if (!existing.rows || existing.rows.length === 0) {
            const settingsUuid = "2aa81079-38c3-4d9f-8380-f50544b32b3d";
            const serverURL = Config.SERVER_URL || "https://app.avniproject.org";
            db.executeSync(
                'INSERT INTO settings ("uuid", "server_url", "log_level", "page_size", "pool_id", "client_id", "dev_skip_validation", "capture_location") VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
                [settingsUuid, serverURL, InitialSettings.logLevel, InitialSettings.pageSize, "", Config.CLIENT_ID || "", 0, 1]
            );
            General.logInfo("SqliteFactory", "Seeded initial Settings row");
        }
    }

    // Column names must match UserInfo schema in openchs-models.
    // If UserInfo schema changes, update this INSERT accordingly.
    static seedUserInfo(db, userInfo) {
        const existing = db.executeSync('SELECT "uuid" FROM user_info WHERE "uuid" = ?', [userInfo.uuid]);
        if (!existing.rows || existing.rows.length === 0) {
            db.executeSync(
                'INSERT INTO user_info ("uuid", "username", "organisation_uuid", "settings", "sync_settings", "name") VALUES (?, ?, ?, ?, ?, ?)',
                [
                    userInfo.uuid,
                    userInfo.username || "",
                    userInfo.organisationUUID || "",
                    typeof userInfo.settings === "string" ? userInfo.settings : JSON.stringify(userInfo.settings || {}),
                    typeof userInfo.syncSettings === "string" ? userInfo.syncSettings : JSON.stringify(userInfo.syncSettings || {}),
                    userInfo.name || "",
                ]
            );
            General.logInfo("SqliteFactory", "Seeded UserInfo row");
        }
    }

    static async createSqliteProxy() {
        const db = await SqliteFactory.createSqliteDb();
        const entityMappingConfig = EntityMappingConfig.getInstance();
        const tableMetaMap = SchemaGenerator.generateAll(entityMappingConfig);
        const realmSchemaMap = SchemaGenerator.buildRealmSchemaMap(entityMappingConfig);
        return new SqliteProxy(db, entityMappingConfig, tableMetaMap, realmSchemaMap);
    }

    static getDbPath() {
        return DB_NAME;
    }
}

export default SqliteFactory;
