echo "Executing the setup for health modules"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/concepts -d @$HEALTH_MODULES_DIR/commonConcepts.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/outpatient/metadata/encounterForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/concepts -d @$HEALTH_MODULES_DIR/outpatient/metadata/concepts.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/concepts -d @$HEALTH_MODULES_DIR/mother/metadata/motherConcepts.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/programs -d @$HEALTH_MODULES_DIR/mother/metadata/motherProgram.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/mother/metadata/motherProgramEnrolmentForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/mother/metadata/motherANCForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/mother/metadata/motherDeliveryForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/mother/metadata/motherAbortionForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/mother/metadata/motherPNCForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/mother/metadata/motherProgramExitForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/concepts -d @$HEALTH_MODULES_DIR/child/metadata/concepts.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/programs -d @$HEALTH_MODULES_DIR/child/metadata/childProgram.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/child/metadata/childProgramEnrolmentForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/child/metadata/childDefaultProgramEncounterForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/child/metadata/childProgramExitForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/ncd/metadata/screeningEncounterForm.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/programs -d @$HEALTH_MODULES_DIR/diabetes/metadata/diabetesProgram.json -H "Content-Type: application/json"
curl -X POST http://$OPENCHS_SERVER:$OPENCHS_SERVER_PORT/forms -d @$HEALTH_MODULES_DIR/diabetes/metadata/diabetesProgramEncounterForm.json -H "Content-Type: application/json"
cp $HEALTH_MODULES_DIR/rules/*.js $SERVER_DIR/external/
cp $HEALTH_MODULES_DIR/customMessages.json $SERVER_DIR/external/
