# tanuh.mk — build automation for the TANUH HealthForge edge-model flavour.
#
# Two-command flow on a TANUH developer's machine:
#   make tanuh-setup     # one-time: generate signing keystore
#   make tanuh-apk       # per-build: encrypt model → assemble signed APK
#
# The on-device runtime is ONNX Runtime Mobile (com.microsoft.onnxruntime:onnxruntime-android)
# and the shipped models are ONNX exports of the clinically-validated MViT2 folds. ONNX Runtime
# is used because its 64-bit native libs are 16 KB-page-aligned (Play targetSdk 35 compliant),
# unlike PyTorch Mobile 1.13.1 (avni-product-ops#186). The ensemble path is `make tanuh-ensemble`.
#
# Plaintext model: tools/edge-model/source/<TANUH_MODEL_KEY>.pt    (gitignored)
# Encrypted output: packages/openchs-android/android/app/src/tanuh/assets/models/
#                   {<TANUH_MODEL_KEY>.bin, registry.json}         (gitignored)
# Signed APK:       packages/openchs-android/android/app/build/outputs/apk/tanuh/release/app-tanuh-release.apk
#
# See tools/edge-model/README.md for the full documentation.

# Override on the command line: TANUH_MODEL_KEY=mvit2_fold5_2_latest_traced make tanuh-apk
# Model file extension for the plaintext sources (onnx by default; the runtime is ONNX Runtime).
TANUH_MODEL_EXT ?= onnx
TANUH_MODEL_KEY ?= mvit2_fold5_2_latest_traced
TANUH_MODEL_SRC := tools/edge-model/source/$(TANUH_MODEL_KEY).$(TANUH_MODEL_EXT)
TANUH_OUT_DIR   := packages/openchs-android/android/app/src/tanuh/assets/models
# Default override captures the PoC pipeline. Swap on the command line for a different model:
#   TANUH_OVERRIDE=tools/edge-model/my-other-model-override.json make tanuh-apk
TANUH_OVERRIDE  := tools/edge-model/tanuh-mvit2-override.json
TANUH_KEYSTORE  := tanuh-release-key.keystore

tanuh-setup: ## One-time: generate the tanuh release keystore.
	@if [ -f "$(TANUH_KEYSTORE)" ]; then \
		echo "Keystore already exists at $(TANUH_KEYSTORE) — skipping. Delete it first to regenerate."; \
		exit 0; \
	fi
	@echo "Generating tanuh release keystore. You will be prompted for passwords and DN."
	@keytool -genkeypair -v \
		-keystore $(TANUH_KEYSTORE) \
		-alias tanuh \
		-keyalg RSA -keysize 2048 \
		-validity 10000
	@echo ""
	@echo "Keystore created. Set these env vars in your shell before running 'make tanuh-apk':"
	@echo "  export tanuh_KEYSTORE_PASSWORD='<the keystore password you just chose>'"
	@echo "  export tanuh_KEY_ALIAS='tanuh'"

tanuh-encrypt: ## Encrypt the plaintext model and emit registry.json.
	@if [ ! -f "$(TANUH_MODEL_SRC)" ]; then \
		echo "ERROR: $(TANUH_MODEL_SRC) not found."; \
		echo "Drop your plaintext .$(TANUH_MODEL_EXT) there (filename = TANUH_MODEL_KEY + .$(TANUH_MODEL_EXT))."; \
		echo "  cp /path/to/$(TANUH_MODEL_KEY).$(TANUH_MODEL_EXT) tools/edge-model/source/"; \
		exit 1; \
	fi
	@mkdir -p $(TANUH_OUT_DIR)
	node tools/edge-model/encrypt-model.js \
		--in $(TANUH_MODEL_SRC) \
		--out-dir $(TANUH_OUT_DIR) \
		--model-key $(TANUH_MODEL_KEY) \
		--override $(TANUH_OVERRIDE) \
		--default-model

tanuh-apk: ## Encrypt single model + assemble signed tanuh release APK.
	$(MAKE) tanuh-encrypt
	$(MAKE) _tanuh-release-assemble

_tanuh-release-assemble: ## (internal) Assemble + sign the tanuh release APK from the current registry.
	@if [ ! -f "$(TANUH_KEYSTORE)" ]; then \
		echo "ERROR: $(TANUH_KEYSTORE) not found. Run 'make tanuh-setup' first."; \
		exit 1; \
	fi
	@if [ -z "$$tanuh_KEYSTORE_PASSWORD" ] || [ -z "$$tanuh_KEY_ALIAS" ]; then \
		echo "ERROR: signing env vars not set. Export tanuh_KEYSTORE_PASSWORD and tanuh_KEY_ALIAS."; \
		echo "(tanuh_KEY_PASSWORD is optional — modern keytool defaults to PKCS12 where it equals the keystore password.)"; \
		exit 1; \
	fi
	# Generate src/framework/Config.js with SERVER_URL from flavor_config.json (tanuh entry).
	# Without this, the app launches with no SERVER_URL configured and shows
	# "Server under maintenance" because /idp-details cannot be reached.
	$(MAKE) as_prod flavor=tanuh
	# Pick the metro bundler config (falls back to metro.config.generic.js for unknown flavours).
	$(MAKE) metro_config flavor=tanuh
	# KEY_STORE_PREFIX prepends to the keystore filename in build.gradle's file(...) lookup;
	# point it at repo root so the keystore generated by `make tanuh-setup` is found.
	cd packages/openchs-android/android; KEY_STORE_PREFIX="$(CURDIR)/" GRADLE_OPTS="$(if $(GRADLE_OPTS),$(GRADLE_OPTS),-Xmx1024m -Xms1024m)" ./gradlew assembleTanuhRelease --stacktrace
	@echo ""
	@echo "Signed APK: packages/openchs-android/android/app/build/outputs/apk/tanuh/release/app-tanuh-release.apk"

# ── 3-fold MViT2 ensemble ───────────────────────────────────────────────────────────
# model6/model8/model8-2 are cross-validation folds of one MViT2 oral-cancer model, shipped
# as ONNX exports and soft-voted in JS by EdgeModelService.runEnsembleInferenceOnImage. Drop
# the 3 plaintext .onnx files (named model6.onnx model8.onnx model8-2.onnx) in
# $(TANUH_ENSEMBLE_SRC_DIR); `tanuh-ensemble` clears the registry then encrypts all three
# (bicubic ensemble override, engine=onnx) under keys mvit2_fold1_6/fold1_8/fold2_8.
TANUH_ENSEMBLE_SRC_DIR  ?= $(HOME)/Desktop/avni/assets/ml
TANUH_ENSEMBLE_OVERRIDE := tools/edge-model/tanuh-ensemble-override.json
# Mapping of source-file basename → registry model key.
TANUH_ENSEMBLE_FOLDS    := model6:mvit2_fold1_6 model8:mvit2_fold1_8 model8-2:mvit2_fold2_8

tanuh-ensemble: ## Encrypt the 3 MViT2 folds into one registry (bicubic ensemble override).
	@for pair in $(TANUH_ENSEMBLE_FOLDS); do \
		src="$(TANUH_ENSEMBLE_SRC_DIR)/$${pair%%:*}.$(TANUH_MODEL_EXT)"; \
		if [ ! -f "$$src" ]; then \
			echo "ERROR: $$src not found."; \
			echo "Set TANUH_ENSEMBLE_SRC_DIR to the dir holding model6.$(TANUH_MODEL_EXT) model8.$(TANUH_MODEL_EXT) model8-2.$(TANUH_MODEL_EXT)"; \
			exit 1; \
		fi; \
	done
	$(MAKE) tanuh-clean
	@mkdir -p $(TANUH_OUT_DIR) tools/edge-model/source
	@for pair in $(TANUH_ENSEMBLE_FOLDS); do \
		file="$${pair%%:*}"; key="$${pair##*:}"; \
		cp "$(TANUH_ENSEMBLE_SRC_DIR)/$$file.$(TANUH_MODEL_EXT)" "tools/edge-model/source/$$key.$(TANUH_MODEL_EXT)"; \
		node tools/edge-model/encrypt-model.js \
			--in "tools/edge-model/source/$$key.$(TANUH_MODEL_EXT)" \
			--out-dir $(TANUH_OUT_DIR) \
			--model-key "$$key" \
			--override $(TANUH_ENSEMBLE_OVERRIDE); \
	done
	@echo ""
	@echo "Encrypted 3 folds into $(TANUH_OUT_DIR)/registry.json: mvit2_fold1_6, mvit2_fold1_8, mvit2_fold2_8"
	@echo "From a form-element rule (soft-vote ensemble → one verdict):"
	@echo "  services.edgeModelService.scheduleImageInference("
	@echo "    ['mvit2_fold1_6','mvit2_fold1_8','mvit2_fold2_8'], imagePath, entity,"
	@echo "    'AI Suspicion Result', {Positive:'Suspicious', Negative:'Non Suspicious'})"

tanuh-ensemble-apk: ## Encrypt the 3 folds + assemble signed tanuh release APK.
	$(MAKE) tanuh-ensemble
	$(MAKE) _tanuh-release-assemble

tanuh-clean: ## Remove the per-build encrypted blob and registry.json.
	rm -f $(TANUH_OUT_DIR)/*.bin $(TANUH_OUT_DIR)/registry.json
	@echo "Cleared $(TANUH_OUT_DIR)/"

# ── Play Store / universal-APK pipeline (ENSEMBLE) ──────────────────────────────────
# Mirrors what CircleCI's release_android_live job (.circleci/config.yml) produces for
# other flavours: a signed AAB for the Play Store and a signed universal APK derived
# from that AAB via bundletool. The shipped model is ALWAYS the 3-fold MViT2 ensemble —
# the AAB target encrypts the folds (`tanuh-ensemble`) before bundling, so the universal
# APK can't accidentally ship the retired single model.
#
# Both targets honour `versionCode` / `versionName` env vars. build.gradle:63-67 reads
# them from the environment; without them, versionCode defaults to 1 (real value
# 8388609 after the 8*1048576 base offset) and versionName defaults to "1".

BUNDLETOOL_VERSION ?= 1.15.1
BUNDLETOOL_JAR     := bundletool.jar
BUNDLETOOL_URL     := https://github.com/google/bundletool/releases/download/$(BUNDLETOOL_VERSION)/bundletool-all-$(BUNDLETOOL_VERSION).jar
TANUH_AAB          := packages/openchs-android/android/app/build/outputs/bundle/tanuhRelease/app-tanuh-release.aab
TANUH_UNIVERSAL    := tanuh-universal.apks

tanuh-aab: tanuh-ensemble ## Build signed tanuh release AAB with the 3-fold ensemble. Pass versionCode=N versionName=X to set them.
	@if [ ! -f "$(TANUH_KEYSTORE)" ]; then \
		echo "ERROR: $(TANUH_KEYSTORE) not found. Run 'make tanuh-setup' first."; \
		exit 1; \
	fi
	@if [ -z "$$tanuh_KEYSTORE_PASSWORD" ] || [ -z "$$tanuh_KEY_ALIAS" ]; then \
		echo "ERROR: signing env vars not set. Export tanuh_KEYSTORE_PASSWORD and tanuh_KEY_ALIAS."; \
		exit 1; \
	fi
	$(MAKE) as_prod flavor=tanuh
	$(MAKE) metro_config flavor=tanuh
	cd packages/openchs-android/android; KEY_STORE_PREFIX="$(CURDIR)/" GRADLE_OPTS="$(if $(GRADLE_OPTS),$(GRADLE_OPTS),-Xmx1024m -Xms1024m)" ./gradlew bundleTanuhRelease --stacktrace
	@echo ""
	@echo "Signed AAB (ensemble): $(TANUH_AAB)"
	@echo "  versionCode env=$${versionCode:-<unset, defaults to 1>}  versionName env=$${versionName:-<unset, defaults to 1>}"

tanuh-universal-apk: tanuh-aab ## Build signed ensemble AAB + signed universal APK via bundletool.
	@if [ ! -f "$(BUNDLETOOL_JAR)" ]; then \
		echo "Downloading bundletool $(BUNDLETOOL_VERSION)..."; \
		curl -fSL -o $(BUNDLETOOL_JAR) $(BUNDLETOOL_URL); \
	fi
	rm -f $(TANUH_UNIVERSAL)
	java -jar $(BUNDLETOOL_JAR) build-apks \
		--bundle=$(TANUH_AAB) \
		--output=$(TANUH_UNIVERSAL) \
		--mode=universal \
		--ks=$(TANUH_KEYSTORE) \
		--ks-pass=pass:$$tanuh_KEYSTORE_PASSWORD \
		--ks-key-alias=$$tanuh_KEY_ALIAS \
		--key-pass=pass:$${tanuh_KEY_PASSWORD:-$$tanuh_KEYSTORE_PASSWORD}
	@echo ""
	@echo "Signed AAB (ensemble): $(TANUH_AAB)"
	@echo "Universal apks (zip):  $(TANUH_UNIVERSAL)"
	@echo "Extract installable APK: unzip -p $(TANUH_UNIVERSAL) universal.apk > tanuh-universal.apk"

# Explicit ensemble-named aliases (tanuh-aab / tanuh-universal-apk now ARE the ensemble path;
# these read clearer at call sites and in CI).
tanuh-ensemble-aab: tanuh-aab ## Alias: signed ensemble AAB.
tanuh-ensemble-universal-apk: tanuh-universal-apk ## Alias: signed ensemble AAB + universal APK.

# Placeholder model setup for local development without TANUH's actual models.
# Downloads the ONNX model zoo's public MobileNetV2 (~14 MB, ImageNet 224x224 RGB,
# 1000-class output) and encrypts it under TANUH_MODEL_KEY=placeholder using
# tools/edge-model/placeholder-override.json. Inference values are unrelated to TANUH's
# domain — use it to verify the build/load/inference plumbing only.
PLACEHOLDER_ONNX_URL := https://github.com/onnx/models/raw/main/validated/vision/classification/mobilenet/model/mobilenetv2-7.onnx
PLACEHOLDER_ONNX_DST := tools/edge-model/source/placeholder.onnx

tanuh-placeholder: ## Download a public placeholder .onnx and encrypt as 'placeholder' for local builds.
	@if [ ! -f "$(PLACEHOLDER_ONNX_DST)" ]; then \
		echo "Downloading placeholder ONNX MobileNetV2 from the onnx/models zoo..."; \
		mkdir -p $$(dirname $(PLACEHOLDER_ONNX_DST)); \
		curl -fSL -o $(PLACEHOLDER_ONNX_DST) $(PLACEHOLDER_ONNX_URL); \
	else \
		echo "$(PLACEHOLDER_ONNX_DST) already present — skipping download."; \
	fi
	@mkdir -p $(TANUH_OUT_DIR)
	node tools/edge-model/encrypt-model.js \
		--in $(PLACEHOLDER_ONNX_DST) \
		--out-dir $(TANUH_OUT_DIR) \
		--model-key placeholder \
		--override tools/edge-model/placeholder-override.json \
		--default-model
	@echo ""
	@echo "Encrypted as 'placeholder' under $(TANUH_OUT_DIR). Now run:"
	@echo "  make run_packager        (in another terminal)"
	@echo "  make run_app_tanuh_dev"
	@echo "Then in a decision rule:"
	@echo "  await params.services.edgeModelService.runInferenceOnImage('placeholder', imagePath)"

# Debug-flavour iteration helpers — install + launch tanuh debug build via gradlew + adb.
# No encryption, no signing, no Metro release bundle. Requires `make run_packager` running
# in another terminal so the app can fetch the dev JS bundle.
#
# Use these for quick iteration on JS / native code without paying the cost of the signed
# release pipeline. To exercise the edge model, run `make tanuh-encrypt` first to populate
# src/tanuh/assets/models/; otherwise the debug build boots with no model registered.

run_app_tanuh: ## Install + launch tanuh debug build, prod backend.
	$(MAKE) as_prod flavor=tanuh
	$(MAKE) _run_app flavor=tanuh

run_app_tanuh_dev: ## Install + launch tanuh debug build, prod backend with dev menu.
	$(MAKE) as_prod_dev flavor=tanuh
	$(MAKE) _run_app flavor=tanuh

# Hyphenated aliases matching the project's `run-app-*` convention.
run-app-tanuh: run_app_tanuh
run-app-tanuh-dev: run_app_tanuh_dev

.PHONY: tanuh-setup tanuh-encrypt tanuh-apk _tanuh-release-assemble tanuh-ensemble tanuh-ensemble-apk tanuh-aab tanuh-universal-apk tanuh-ensemble-aab tanuh-ensemble-universal-apk tanuh-clean tanuh-placeholder run_app_tanuh run_app_tanuh_dev run-app-tanuh run-app-tanuh-dev
