# tanuh.mk — build automation for the TANUH HealthForge edge-model flavour.
#
# Two-command flow on a TANUH developer's machine:
#   make tanuh-setup     # one-time: generate signing keystore
#   make tanuh-apk       # per-build: encrypt model → assemble signed APK
#
# The on-device runtime is PyTorch Mobile (org.pytorch:pytorch_android:1.13.1) and the
# bundled model is a TorchScript .pt file. Versions are pinned to match the TANUH AI team's
# PoC at ~/IdeaProjects/aiapp — clinical accuracy was validated against that exact runtime.
#
# Plaintext model: tools/edge-model/source/<TANUH_MODEL_KEY>.pt    (gitignored)
# Encrypted output: packages/openchs-android/android/app/src/tanuh/assets/models/
#                   {<TANUH_MODEL_KEY>.bin, registry.json}         (gitignored)
# Signed APK:       packages/openchs-android/android/app/build/outputs/apk/tanuh/release/app-tanuh-release.apk
#
# See tools/edge-model/README.md for the full documentation.

# Override on the command line: TANUH_MODEL_KEY=mvit2_fold5_2_latest_traced make tanuh-apk
TANUH_MODEL_KEY ?= mvit2_fold5_2_latest_traced
TANUH_MODEL_SRC := tools/edge-model/source/$(TANUH_MODEL_KEY).pt
TANUH_OUT_DIR   := packages/openchs-android/android/app/src/tanuh/assets/models
# Default override captures the PoC pipeline. Swap on the command line for a different model:
#   TANUH_OVERRIDE=tools/edge-model/my-other-model-override.json make tanuh-apk
TANUH_OVERRIDE  := tools/edge-model/tanuh-mvit2-override.json
TANUH_KEYSTORE  := tanuh-release-key.keystore

tanuh-setup: ## One-time: generate the tanuh release keystore.
	@if [ -f "$(TANUH_KEYSTORE)" ]; then \
		echo "Keystore already exists at $(TANUH_KEYSTORE) — skipping. Delete it first to regenerate."; \
		exit 0; \
	fi
	@echo "Generating tanuh release keystore. You will be prompted for passwords and DN."
	@keytool -genkeypair -v \
		-keystore $(TANUH_KEYSTORE) \
		-alias tanuh \
		-keyalg RSA -keysize 2048 \
		-validity 10000
	@echo ""
	@echo "Keystore created. Set these env vars in your shell before running 'make tanuh-apk':"
	@echo "  export tanuh_KEYSTORE_PASSWORD='<the keystore password you just chose>'"
	@echo "  export tanuh_KEY_ALIAS='tanuh'"

tanuh-encrypt: ## Encrypt the plaintext model and emit registry.json.
	@if [ ! -f "$(TANUH_MODEL_SRC)" ]; then \
		echo "ERROR: $(TANUH_MODEL_SRC) not found."; \
		echo "Drop your plaintext .pt there (filename = TANUH_MODEL_KEY + .pt)."; \
		echo "  cp /path/to/$(TANUH_MODEL_KEY).pt tools/edge-model/source/"; \
		exit 1; \
	fi
	@mkdir -p $(TANUH_OUT_DIR)
	node tools/edge-model/encrypt-model.js \
		--in $(TANUH_MODEL_SRC) \
		--out-dir $(TANUH_OUT_DIR) \
		--model-key $(TANUH_MODEL_KEY) \
		--override $(TANUH_OVERRIDE) \
		--default-model

tanuh-apk: tanuh-encrypt ## Encrypt model + assemble signed tanuh release APK.
	@if [ ! -f "$(TANUH_KEYSTORE)" ]; then \
		echo "ERROR: $(TANUH_KEYSTORE) not found. Run 'make tanuh-setup' first."; \
		exit 1; \
	fi
	@if [ -z "$$tanuh_KEYSTORE_PASSWORD" ] || [ -z "$$tanuh_KEY_ALIAS" ]; then \
		echo "ERROR: signing env vars not set. Export tanuh_KEYSTORE_PASSWORD and tanuh_KEY_ALIAS."; \
		echo "(tanuh_KEY_PASSWORD is optional — modern keytool defaults to PKCS12 where it equals the keystore password.)"; \
		exit 1; \
	fi
	# Generate src/framework/Config.js with SERVER_URL from flavor_config.json (tanuh entry).
	# Without this, the app launches with no SERVER_URL configured and shows
	# "Server under maintenance" because /idp-details cannot be reached.
	$(MAKE) as_prod flavor=tanuh
	# Pick the metro bundler config (falls back to metro.config.generic.js for unknown flavours).
	$(MAKE) metro_config flavor=tanuh
	# KEY_STORE_PREFIX prepends to the keystore filename in build.gradle's file(...) lookup;
	# point it at repo root so the keystore generated by `make tanuh-setup` is found.
	cd packages/openchs-android/android; KEY_STORE_PREFIX="$(CURDIR)/" GRADLE_OPTS="$(if $(GRADLE_OPTS),$(GRADLE_OPTS),-Xmx1024m -Xms1024m)" ./gradlew assembleTanuhRelease --stacktrace
	@echo ""
	@echo "Signed APK: packages/openchs-android/android/app/build/outputs/apk/tanuh/release/app-tanuh-release.apk"

tanuh-clean: ## Remove the per-build encrypted blob and registry.json.
	rm -f $(TANUH_OUT_DIR)/*.bin $(TANUH_OUT_DIR)/registry.json
	@echo "Cleared $(TANUH_OUT_DIR)/"

# ── Play Store / universal-APK pipeline ─────────────────────────────────────────────
# Mirrors what CircleCI's release_android_live job (.circleci/config.yml) produces for
# other flavours: a signed AAB for the Play Store and a signed universal APK derived
# from that AAB via bundletool. The per-arch APK pipeline is `make tanuh-apk`; this is
# the bundle path that exercises the AAB toolchain end-to-end.
#
# Both targets honour `versionCode` / `versionName` env vars. build.gradle:63-67 reads
# them from the environment; without them, versionCode defaults to 1 (real value
# 8388609 after the 8*1048576 base offset) and versionName defaults to "1".

BUNDLETOOL_VERSION ?= 1.15.1
BUNDLETOOL_JAR     := bundletool.jar
BUNDLETOOL_URL     := https://github.com/google/bundletool/releases/download/$(BUNDLETOOL_VERSION)/bundletool-all-$(BUNDLETOOL_VERSION).jar
TANUH_AAB          := packages/openchs-android/android/app/build/outputs/bundle/tanuhRelease/app-tanuh-release.aab
TANUH_UNIVERSAL    := tanuh-universal.apks

tanuh-aab: tanuh-encrypt ## Build signed tanuh release AAB. Pass versionCode=N versionName=X to set them.
	@if [ ! -f "$(TANUH_KEYSTORE)" ]; then \
		echo "ERROR: $(TANUH_KEYSTORE) not found. Run 'make tanuh-setup' first."; \
		exit 1; \
	fi
	@if [ -z "$$tanuh_KEYSTORE_PASSWORD" ] || [ -z "$$tanuh_KEY_ALIAS" ]; then \
		echo "ERROR: signing env vars not set. Export tanuh_KEYSTORE_PASSWORD and tanuh_KEY_ALIAS."; \
		exit 1; \
	fi
	$(MAKE) as_prod flavor=tanuh
	$(MAKE) metro_config flavor=tanuh
	cd packages/openchs-android/android; KEY_STORE_PREFIX="$(CURDIR)/" GRADLE_OPTS="$(if $(GRADLE_OPTS),$(GRADLE_OPTS),-Xmx1024m -Xms1024m)" ./gradlew bundleTanuhRelease --stacktrace
	@echo ""
	@echo "Signed AAB: $(TANUH_AAB)"
	@echo "  versionCode env=$${versionCode:-<unset, defaults to 1>}  versionName env=$${versionName:-<unset, defaults to 1>}"

tanuh-universal-apk: tanuh-aab ## Build signed AAB + signed universal APK via bundletool.
	@if [ ! -f "$(BUNDLETOOL_JAR)" ]; then \
		echo "Downloading bundletool $(BUNDLETOOL_VERSION)..."; \
		curl -fSL -o $(BUNDLETOOL_JAR) $(BUNDLETOOL_URL); \
	fi
	rm -f $(TANUH_UNIVERSAL)
	java -jar $(BUNDLETOOL_JAR) build-apks \
		--bundle=$(TANUH_AAB) \
		--output=$(TANUH_UNIVERSAL) \
		--mode=universal \
		--ks=$(TANUH_KEYSTORE) \
		--ks-pass=pass:$$tanuh_KEYSTORE_PASSWORD \
		--ks-key-alias=$$tanuh_KEY_ALIAS \
		--key-pass=pass:$${tanuh_KEY_PASSWORD:-$$tanuh_KEYSTORE_PASSWORD}
	@echo ""
	@echo "Signed AAB:           $(TANUH_AAB)"
	@echo "Universal apks (zip): $(TANUH_UNIVERSAL)"
	@echo "Extract installable APK: unzip -p $(TANUH_UNIVERSAL) universal.apk > tanuh-universal.apk"

# Placeholder model setup for local development without TANUH's actual .pt.
# Downloads PyTorch's official Hello World traced MobileNetV2 (~20 MB, ImageNet 224x224 RGB,
# 1000-class output) and encrypts it under TANUH_MODEL_KEY=placeholder using
# tools/edge-model/placeholder-override.json. Inference values are unrelated to TANUH's
# domain — use it to verify the build/load/inference plumbing only.
PLACEHOLDER_PT_URL := https://raw.githubusercontent.com/pytorch/android-demo-app/master/HelloWorldApp/app/src/main/assets/model.pt
PLACEHOLDER_PT_DST := tools/edge-model/source/placeholder.pt

tanuh-placeholder: ## Download a public placeholder .pt and encrypt as 'placeholder' for local builds.
	@if [ ! -f "$(PLACEHOLDER_PT_DST)" ]; then \
		echo "Downloading placeholder model from PyTorch's android-demo-app..."; \
		mkdir -p $$(dirname $(PLACEHOLDER_PT_DST)); \
		curl -fSL -o $(PLACEHOLDER_PT_DST) $(PLACEHOLDER_PT_URL); \
	else \
		echo "$(PLACEHOLDER_PT_DST) already present — skipping download."; \
	fi
	@mkdir -p $(TANUH_OUT_DIR)
	node tools/edge-model/encrypt-model.js \
		--in $(PLACEHOLDER_PT_DST) \
		--out-dir $(TANUH_OUT_DIR) \
		--model-key placeholder \
		--override tools/edge-model/placeholder-override.json \
		--default-model
	@echo ""
	@echo "Encrypted as 'placeholder' under $(TANUH_OUT_DIR). Now run:"
	@echo "  make run_packager        (in another terminal)"
	@echo "  make run_app_tanuh_dev"
	@echo "Then in a decision rule:"
	@echo "  await params.services.edgeModelService.runInferenceOnImage('placeholder', imagePath)"

# Debug-flavour iteration helpers — install + launch tanuh debug build via gradlew + adb.
# No encryption, no signing, no Metro release bundle. Requires `make run_packager` running
# in another terminal so the app can fetch the dev JS bundle.
#
# Use these for quick iteration on JS / native code without paying the cost of the signed
# release pipeline. To exercise the edge model, run `make tanuh-encrypt` first to populate
# src/tanuh/assets/models/; otherwise the debug build boots with no model registered.

run_app_tanuh: ## Install + launch tanuh debug build, prod backend.
	$(MAKE) as_prod flavor=tanuh
	$(MAKE) _run_app flavor=tanuh

run_app_tanuh_dev: ## Install + launch tanuh debug build, prod backend with dev menu.
	$(MAKE) as_prod_dev flavor=tanuh
	$(MAKE) _run_app flavor=tanuh

# Hyphenated aliases matching the project's `run-app-*` convention.
run-app-tanuh: run_app_tanuh
run-app-tanuh-dev: run_app_tanuh_dev

.PHONY: tanuh-setup tanuh-encrypt tanuh-apk tanuh-aab tanuh-universal-apk tanuh-clean tanuh-placeholder run_app_tanuh run_app_tanuh_dev run-app-tanuh run-app-tanuh-dev
